### Users - SignUp
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "username": "johdoe2",
    "name": "John Doe",
    "email": "johndoe2@email.com",
    "password": "12345"
}

### Users - Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "johdoe",
    "password": "12345"
}

### Users - Logout
POST http://localhost:3000/api/users/logout
