### Users - Profile
GET http://localhost:3000/api/users/profile/johndoe

### Users - SignUp
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "username": "johdoe2",
    "name": "John Doe",
    "email": "johndoe2@email.com",
    "password": "12345"
}

### Users - Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "johdoe",
    "password": "12345"
}

### Users - Logout
POST http://localhost:3000/api/users/logout

### User - Follow / Unfollow
POST http://localhost:3000/api/users/follow/67a9e357f61c910f68ed0412

### User - Update
POST http://localhost:3000/api/users/update/67a9e2b2f61c910f68ed040d
Content-Type: application/json

{
    "username": "johdoe"
}

### Posts - Create
POST http://localhost:3000/api/posts/create
Content-Type: application/json

{
    "postedBy": "67a9e2b2f61c910f68ed040d",
    "text": "this is my first post"
}